server:
  port: 8081

#logging:
#  level:
#    org.springframework: DEBUG

spring:
  messages:
    basename: messages
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
  security:
    user:
      name: test
      password: pwd

management:
  endpoints:
    web:
      exposure:
        include: "*"

